config/routes.rb
PuppyBook::Application.routes.draw do

 resources :owners, only: [:index, :new, :create, :show]

 resources :dogs, only: [:index, :new, :create, :edit, :update]

end

app/models/dog.rb
class Dog < ActiveRecord::Base
  belongs_to :owner

  validates :dog_name, presence: true
  validates :owner_id, presence: true
end

app/models/owner.rb
class Owner < ActiveRecord::Base

  has_many :dogs

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
  validates :dog, presence: true


  def full_name
    first_name + ' ' + last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  def new
    @dog = Dog.new
    @owners = Owner.all.map { |o| [o.full_name, o.id]}
  end

  def create
    @dog = Dog.new(dog_params)
    if @dog.save
      redirect_to "/owners/#{@dog.owner_id}", notice: 'Dog was successfully registered'
    else
      render 'new'
    end
  end

  def edit
    @dog = Dog.find(params[:id])
  end

  def update
    @dog = Dog.find(params[:id])
    if @dog.update(params.require(:dog).permit(:dog_name, :breed, :owner_id))
      redirect_to owner_path(@dog.owner_id), notice: 'Dog was successfully edited'
    else
      render :edit
    end

  end
  def dog_params
    params.require(:dog).permit(:dog_name, :breed, :owner_id)
  end

end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

  def new
    @owner = Owner.new
    @dog = Dog.new
  end

  def create
    @owner = Owner.new(owner_params)
    if @owner.save
      @dog = Dog.create!(dog_name: @owner.dog, owner_id: @owner.id)
      redirect_to '/owners', notice: 'Dog was successfully registered'
    else
      render 'new'
    end
  end

  def index
    @owners = Owner.all
  end

  def show
    @owner = Owner.find(params[:id])
  end

  def owner_params
    params.require(:owner).permit(:first_name, :last_name, :email, :dog)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/dogs/edit.html.erb
<h1>Edit Dog</h1>

<%= simple_form_for(@dog) do |f| %>
  <%= f.input :dog_name, label: 'Dog Name' %>
  <%= f.input :breed %>
  <%= f.input :owner_id, label: 'Owner', collection: @owners %>


  <%= f.button :submit, 'Edit Dog' %>
<% end %>

app/views/dogs/new.html.erb
<h1>Register Dog Here</h1>

<%= simple_form_for(@dog) do |f| %>
  <%= f.input :dog_name, label: 'Dog Name' %>
  <%= f.input :breed %>
  <%= f.input :owner_id, label: 'Owner', collection: @owners %>


  <%= f.button :submit, 'Register Dog' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PuppyBook</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%- if flash[:notice].present? -%>
    <p><%= flash[:notice] %></p>
  <%- end -%>

  <%= yield %>

</body>
</html>

app/views/owners/index.html.erb
<h1>PuppyBook</h1>

<h2>Registered Dog Owners</h2>
<% if @owners.present? %>
  <ul>
    <% @owners.each do |owner| %>
      <li><%=link_to "#{owner.full_name}", owner %></li>
    <% end %>
  </ul>
<% else %>
  <p>--no registered dog owners--</p>
<% end %>

<%= link_to 'Register Dog', new_owner_path %>

app/views/owners/new.html.erb
<h1>Register Dog Here</h1>

<%= simple_form_for(@owner) do |f| %>
  <%= f.input :first_name, label: 'First Name' %>
  <%= f.input :last_name, label: 'Last Name' %>
  <%= f.input :email %>
  <%= f.input :dog, label: 'Dog Name' %>

  <%= f.button :submit, 'Register Dog' %>
<% end %>

app/views/owners/show.html.erb
<h1><%= @owner.full_name %></h1>

<p><%= @owner.email %></p>

<h2>Registered Dogs</h2>
<h4>(Click on Dog to Edit)</h4>
<ul>
  <% @owner.dogs.each do |dog| %>
    <% if dog.breed != nil %>
      <li><%= link_to "#{dog.dog_name}", "/dogs/#{dog.id}/edit"%><br>
        Breed: <%= dog.breed %></li>
    <% else %>
      <li><%= link_to "#{dog.dog_name}", "/dogs/#{dog.id}/edit" %></li>
    <% end %>
  <% end %>
</ul>



<%= link_to "Add Dog", '/dogs/new' %><br>
<%= link_to "Back to Owners", owners_path %>